# create_baseline_notebook.py
import json
import os

def create_baseline_notebook():
    """Cria o notebook completo do Modelo Baseline em formato .ipynb"""
    
    notebook_content = {
        "cells": [
            {
                "cell_type": "markdown",
                "id": "introducao",
                "metadata": {},
                "source": [
                    "# 🎯 ETAPA 3: MODELO BASELINE - REGRESSÃO LINEAR\n",
                    "\n",
                    "## 📋 OBJETIVOS\n",
                    "- Criar primeiro modelo de Machine Learning\n",
                    "- Avaliar performance com métricas robustas\n",
                    "- Identificar overfitting\n",
                    "- Analisar features mais importantes\n",
                    "- Estabelecer baseline para comparação futura\n",
                    "\n",
                    "## 🛠️ TÉCNICAS UTILIZADAS\n",
                    "- Regressão Linear\n",
                    "- Validação Train/Validation/Test (60/20/20)\n",
                    "- Métricas: MSE, RMSE, MAE, R²\n",
                    "- Análise de Resíduos\n",
                    "- Feature Importance\n",
                    "\n",
                    "## 📁 ARQUIVOS GERADOS\n",
                    "- `models/modelo_baseline.pkl` - Modelo treinado\n",
                    "- `analise_baseline.png` - Visualizações do modelo"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "importacoes",
                "metadata": {},
                "source": [
                    "## 1. 📚 IMPORTAÇÕES E CONFIGURAÇÕES"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "importacoes-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- BIBLIOTECAS ESSENCIAIS ---\n",
                    "import pandas as pd\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "from sklearn.model_selection import train_test_split\n",
                    "from sklearn.linear_model import LinearRegression\n",
                    "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
                    "import joblib\n",
                    "import os\n",
                    "\n",
                    "# --- CONFIGURAÇÕES DE VISUALIZAÇÃO ---\n",
                    "sns.set_style(\"whitegrid\")\n",
                    "plt.rcParams['figure.figsize'] = (12, 6)\n",
                    "plt.rcParams['font.size'] = 12\n",
                    "\n",
                    "# Cores profissionais para os gráficos\n",
                    "CORES = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']\n",
                    "\n",
                    "print(\"✅ Bibliotecas importadas e configuradas!\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "carregar-dados",
                "metadata": {},
                "source": [
                    "## 2. 📥 CARREGAR DADOS PRÉ-PROCESSADOS"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "carregar-dados-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- CARREGAR DATASET JÁ PRÉ-PROCESSADO ---\n",
                    "print(\"📥 Carregando dataset pré-processado...\")\n",
                    "df = pd.read_csv(\"dataset_preprocessado.csv\")\n",
                    "\n",
                    "# Verificação rápida do dataset\n",
                    "print(f\"📊 Dimensões do dataset: {df.shape}\")\n",
                    "print(f\"🔍 Amostra das primeiras linhas:\")\n",
                    "display(df.head(3))\n",
                    "\n",
                    "# Informações sobre tipos de dados\n",
                    "print(\"\\n📋 Tipos de dados:\")\n",
                    "print(df.dtypes.value_counts())\n",
                    "\n",
                    "print(\"\\n✅ Dataset carregado com sucesso!\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "preparar-dados",
                "metadata": {},
                "source": [
                    "## 3. 🎯 PREPARAR DADOS PARA MODELAGEM"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "preparar-dados-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- SEPARAR FEATURES (X) E TARGET (y) ---\n",
                    "# ⚠️ AJUSTE: Verifique se 'monthly_sales' é sua coluna target!\n",
                    "target_column = 'monthly_sales'  # Altere se necessário\n",
                    "\n",
                    "if target_column not in df.columns:\n",
                    "    print(\"❌ ERRO: Coluna target não encontrada!\")\n",
                    "    print(f\"Colunas disponíveis: {list(df.columns)}\")\n",
                    "else:\n",
                    "    X = df.drop(target_column, axis=1)  # Todas as colunas EXCETO target\n",
                    "    y = df[target_column]               # Apenas a coluna target\n",
                    "    \n",
                    "    print(f\"🎯 Variável target: {target_column}\")\n",
                    "    print(f\"📈 Número de features: {X.shape[1]}\")\n",
                    "    print(f\"📊 Número de observações: {X.shape[0]}\")\n",
                    "    \n",
                    "    # Estatísticas da variável target\n",
                    "    print(f\"\\n📋 Estatísticas da variável target:\")\n",
                    "    print(f\"   Média: {y.mean():.2f}\")\n",
                    "    print(f\"   Desvio padrão: {y.std():.2f}\")\n",
                    "    print(f\"   Mínimo: {y.min():.2f}\")\n",
                    "    print(f\"   Máximo: {y.max():.2f}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "divisao-dados",
                "metadata": {},
                "source": [
                    "## 4. 📊 DIVISÃO DOS DADOS (60% TREINO / 20% VALIDAÇÃO / 20% TESTE)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "divisao-dados-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- ESTRATÉGIA DE DIVISÃO ---\n",
                    "# 1. Primeiro: Separar 20% para teste (guardado para etapa final)\n",
                    "# 2. Depois: Dividir o restante em 75% treino / 25% validação\n",
                    "# Resultado: 60% Treino, 20% Validação, 20% Teste\n",
                    "\n",
                    "print(\"📊 Iniciando divisão dos dados...\")\n",
                    "\n",
                    "# Primeira divisão: 80% temporário / 20% teste\n",
                    "X_temp, X_test, y_temp, y_test = train_test_split(\n",
                    "    X, y, \n",
                    "    test_size=0.2,       # 20% para teste\n",
                    "    random_state=42,     # Semente para reproducibilidade\n",
                    "    shuffle=True         # Embaralhar dados\n",
                    ")\n",
                    "\n",
                    "# Segunda divisão: 75% treino / 25% validação do temporário\n",
                    "X_train, X_val, y_train, y_val = train_test_split(\n",
                    "    X_temp, y_temp,\n",
                    "    test_size=0.25,      # 25% de 80% = 20% do total\n",
                    "    random_state=42,\n",
                    "    shuffle=True\n",
                    ")\n",
                    "\n",
                    "# --- VERIFICAÇÃO DA DIVISÃO ---\n",
                    "print(\"✅ Divisão concluída com sucesso!\")\n",
                    "print(f\"\\n📋 DISTRIBUIÇÃO DOS DADOS:\")\n",
                    "print(f\"   🟢 Treino:      {X_train.shape[0]:>5} amostras ({X_train.shape[0]/len(X)*100:.1f}%)\")\n",
                    "print(f\"   🟡 Validação:   {X_val.shape[0]:>5} amostras ({X_val.shape[0]/len(X)*100:.1f}%)\")\n",
                    "print(f\"   🔴 Teste:       {X_test.shape[0]:>5} amostras ({X_test.shape[0]/len(X)*100:.1f}%)\")\n",
                    "print(f\"   📊 Total:       {len(X):>5} amostras (100.0%)\")\n",
                    "\n",
                    "print(f\"\\n🎯 IMPORTANTE: Dados de teste serão guardados para a etapa final!\")\n",
                    "print(\"   Usaremos apenas treino e validação nesta etapa.\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "treinar-modelo",
                "metadata": {},
                "source": [
                    "## 5. 🤖 TREINAR MODELO DE REGRESSÃO LINEAR"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "treinar-modelo-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- MODELO BASELINE: REGRESSÃO LINEAR ---\n",
                    "print(\"🤖 Iniciando treinamento do modelo...\")\n",
                    "\n",
                    "# Criar e treinar o modelo\n",
                    "modelo_baseline = LinearRegression()\n",
                    "\n",
                    "print(\"📦 Parâmetros do modelo:\")\n",
                    "print(f\"   Algoritmo: {modelo_baseline.__class__.__name__}\")\n",
                    "print(f\"   Fit intercept: {modelo_baseline.fit_intercept}\")\n",
                    "\n",
                    "# Treinar o modelo\n",
                    "modelo_baseline.fit(X_train, y_train)\n",
                    "\n",
                    "print(\"\\n✅ Modelo treinado com sucesso!\")\n",
                    "print(f\"   Número de coeficientes: {len(modelo_baseline.coef_)}\")\n",
                    "print(f\"   Intercept: {modelo_baseline.intercept_:.4f}\")\n",
                    "\n",
                    "# Fazer previsões\n",
                    "y_pred_train = modelo_baseline.predict(X_train)\n",
                    "y_pred_val = modelo_baseline.predict(X_val)\n",
                    "\n",
                    "print(\"\\n🎯 Previsões realizadas:\")\n",
                    "print(f\"   Previsões treino:   {len(y_pred_train)}\")\n",
                    "print(f\"   Previsões validação: {len(y_pred_val)}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "metricas-avaliacao",
                "metadata": {},
                "source": [
                    "## 6. 📈 CALCULAR E ANALISAR MÉTRICAS DE PERFORMANCE"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "metricas-avaliacao-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- FUNÇÃO PARA CÁLCULO DAS MÉTRICAS ---\n",
                    "def calcular_metricas_completas(y_real, y_pred, nome_conjunto):\n",
                    "    \"\"\"Calcula todas as métricas de regressão\"\"\"\n",
                    "    \n",
                    "    mse = mean_squared_error(y_real, y_pred)\n",
                    "    rmse = np.sqrt(mse)\n",
                    "    mae = mean_absolute_error(y_real, y_pred)\n",
                    "    r2 = r2_score(y_real, y_pred)\n",
                    "    \n",
                    "    return {\n",
                    "        'MSE': mse,\n",
                    "        'RMSE': rmse,\n",
                    "        'MAE': mae,\n",
                    "        'R²': r2\n",
                    "    }\n",
                    "\n",
                    "def interpretar_metricas(metricas, nome_conjunto):\n",
                    "    \"\"\"Exibe e interpreta as métricas de forma amigável\"\"\"\n",
                    "    \n",
                    "    print(f\"\\n📊 MÉTRICAS - {nome_conjunto.upper()}:\")\n",
                    "    print(\"-\" * 40)\n",
                    "    print(f\"   📉 MSE:  {metricas['MSE']:>10.4f}\")\n",
                    "    print(f\"   📏 RMSE: {metricas['RMSE']:>10.4f}\")\n",
                    "    print(f\"   📐 MAE:  {metricas['MAE']:>10.4f}\")\n",
                    "    print(f\"   🎯 R²:   {metricas['R²']:>10.4f}\")\n",
                    "    \n",
                    "    # Interpretação do R²\n",
                    "    r2 = metricas['R²']\n",
                    "    if r2 > 0.7:\n",
                    "        interpretacao = \"✅ EXCELENTE - Modelo explica bem a variância\"\n",
                    "    elif r2 > 0.5:\n",
                    "        interpretacao = \"⚠️  BOM - Poder explicativo moderado\"\n",
                    "    elif r2 > 0.3:\n",
                    "        interpretacao = \"🔶 RAZOÁVEL - Algum poder explicativo\"\n",
                    "    else:\n",
                    "        interpretacao = \"❌ BAIXO - Necessita melhorias\"\n",
                    "        \n",
                    "    print(f\"\\n   💡 Interpretação R²: {interpretacao}\")\n",
                    "\n",
                    "# --- CALCULAR MÉTRICAS PARA TREINO E VALIDAÇÃO ---\n",
                    "metricas_treino = calcular_metricas_completas(y_train, y_pred_train, \"treino\")\n",
                    "metricas_validacao = calcular_metricas_completas(y_val, y_pred_val, \"validação\")\n",
                    "\n",
                    "# Exibir resultados\n",
                    "interpretar_metricas(metricas_treino, \"Conjunto de Treino\")\n",
                    "interpretar_metricas(metricas_validacao, \"Conjunto de Validação\")\n",
                    "\n",
                    "# --- ANÁLISE DE OVERFITTING ---\n",
                    "diferenca_r2 = abs(metricas_treino['R²'] - metricas_validacao['R²'])\n",
                    "\n",
                    "print(f\"\\n🔍 ANÁLISE DE OVERFITTING:\")\n",
                    "print(\"-\" * 40)\n",
                    "print(f\"   Diferença R² (treino - validação): {diferenca_r2:.4f}\")\n",
                    "\n",
                    "if diferenca_r2 < 0.05:\n",
                    "    print(\"   ✅ EXCELENTE - Modelo generaliza muito bem\")\n",
                    "elif diferenca_r2 < 0.10:\n",
                    "    print(\"   ⚠️  BOM - Pequeno overfitting, aceitável\")\n",
                    "elif diferenca_r2 < 0.15:\n",
                    "    print(\"   🔶 MODERADO - Overfitting presente\")\n",
                    "else:\n",
                    "    print(\"   ❌ ALTO - Overfitting significativo\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "feature-importance",
                "metadata": {},
                "source": [
                    "## 7. 🎯 ANÁLISE DAS FEATURES MAIS IMPORTANTES"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "feature-importance-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- FEATURE IMPORTANCE PARA REGRESSÃO LINEAR ---\n",
                    "print(\"🎯 Analisando features mais importantes...\")\n",
                    "\n",
                    "# Criar DataFrame com importância das features\n",
                    "importancia_features = pd.DataFrame({\n",
                    "    'Feature': X.columns,\n",
                    "    'Coeficiente': modelo_baseline.coef_,\n",
                    "    'Importância_Absoluta': abs(modelo_baseline.coef_)\n",
                    "})\n",
                    "\n",
                    "# Ordenar por importância\n",
                    "importancia_features = importancia_features.sort_values('Importância_Absoluta', ascending=False)\n",
                    "\n",
                    "print(f\"\\n📊 TOP 10 FEATURES MAIS IMPORTANTES:\")\n",
                    "print(\"-\" * 60)\n",
                    "for i, row in importancia_features.head(10).iterrows():\n",
                    "    sinal = \"➕\" if row['Coeficiente'] > 0 else \"➖\"\n",
                    "    print(f\"   {sinal} {row['Feature']:<30} | Coef: {row['Coeficiente']:>8.4f} | Impacto: {row['Importância_Absoluta']:>8.4f}\")\n",
                    "\n",
                    "# Visualização das top features\n",
                    "plt.figure(figsize=(10, 6))\n",
                    "top_10 = importancia_features.head(10)\n",
                    "cores = ['#2E86AB' if x > 0 else '#A23B72' for x in top_10['Coeficiente']]\n",
                    "\n",
                    "plt.barh(top_10['Feature'], top_10['Importância_Absoluta'], color=cores)\n",
                    "plt.xlabel('Importância Absoluta')\n",
                    "plt.title('Top 10 Features Mais Importantes - Modelo Baseline')\n",
                    "plt.gca().invert_yaxis()\n",
                    "plt.grid(axis='x', alpha=0.3)\n",
                    "plt.tight_layout()\n",
                    "plt.show()\n",
                    "\n",
                    "print(f\"\\n💡 INSIGHTS DAS FEATURES:\")\n",
                    "print(f\"   • Features com coeficiente POSITIVO aumentam as vendas\")\n",
                    "print(f\"   • Features com coeficiente NEGATIVO diminuem as vendas\")\n",
                    "print(f\"   • Magnitude indica força do impacto\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "visualizacoes",
                "metadata": {},
                "source": [
                    "## 8. 📊 VISUALIZAÇÕES PROFISSIONAIS DO MODELO"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "visualizacoes-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- GRÁFICOS COMPLETOS DE ANÁLISE ---\n",
                    "print(\"📊 Gerando visualizações profissionais...\")\n",
                    "\n",
                    "fig, axes = plt.subplots(2, 2, figsize=(15, 12))\n",
                    "fig.suptitle('📈 ANÁLISE COMPLETA - MODELO BASELINE', fontsize=16, fontweight='bold')\n",
                    "\n",
                    "# 1. PREDIÇÕES vs VALORES REAIS (Validação)\n",
                    "axes[0,0].scatter(y_val, y_pred_val, alpha=0.6, color='#2E86AB')\n",
                    "axes[0,0].plot([y_val.min(), y_val.max()], [y_val.min(), y_val.max()], '--', color='#F18F01', linewidth=2, label='Linha Perfeita')\n",
                    "axes[0,0].set_xlabel('Valores Reais')\n",
                    "axes[0,0].set_ylabel('Predições')\n",
                    "axes[0,0].set_title('Predições vs Valores Reais (Validação)')\n",
                    "axes[0,0].legend()\n",
                    "axes[0,0].grid(True, alpha=0.3)\n",
                    "\n",
                    "# 2. DISTRIBUIÇÃO DOS RESÍDUOS\n",
                    "residuos = y_val - y_pred_val\n",
                    "axes[0,1].hist(residuos, bins=30, alpha=0.7, color='#A23B72', edgecolor='black')\n",
                    "axes[0,1].axvline(x=0, color='red', linestyle='--', linewidth=2, label='Resíduo Zero')\n",
                    "axes[0,1].set_xlabel('Resíduos (Real - Predito)')\n",
                    "axes[0,1].set_ylabel('Frequência')\n",
                    "axes[0,1].set_title('Distribuição dos Resíduos')\n",
                    "axes[0,1].legend()\n",
                    "axes[0,1].grid(True, alpha=0.3)\n",
                    "\n",
                    "# 3. RESÍDUOS vs PREDIÇÕES\n",
                    "axes[1,0].scatter(y_pred_val, residuos, alpha=0.6, color='#C73E1D')\n",
                    "axes[1,0].axhline(y=0, color='red', linestyle='--', linewidth=2, label='Linha Zero')\n",
                    "axes[1,0].set_xlabel('Predições')\n",
                    "axes[1,0].set_ylabel('Resíduos')\n",
                    "axes[1,0].set_title('Resíduos vs Predições')\n",
                    "axes[1,0].legend()\n",
                    "axes[1,0].grid(True, alpha=0.3)\n",
                    "\n",
                    "# 4. COMPARAÇÃO TREINO vs VALIDAÇÃO\n",
                    "metricas_comparacao = pd.DataFrame({\n",
                    "    'Conjunto': ['Treino', 'Validação'],\n",
                    "    'R²': [metricas_treino['R²'], metricas_validacao['R²']],\n",
                    "    'RMSE': [metricas_treino['RMSE'], metricas_validacao['RMSE']]\n",
                    "})\n",
                    "\n",
                    "x_pos = np.arange(2)\n",
                    "largura = 0.35\n",
                    "\n",
                    "axes[1,1].bar(x_pos - largura/2, metricas_comparacao['R²'], largura, label='R²', color='#2E86AB', alpha=0.8)\n",
                    "axes[1,1].bar(x_pos + largura/2, metricas_comparacao['RMSE'], largura, label='RMSE', color='#A23B72', alpha=0.8)\n",
                    "axes[1,1].set_xlabel('Conjunto de Dados')\n",
                    "axes[1,1].set_ylabel('Valor da Métrica')\n",
                    "axes[1,1].set_title('Comparação: Treino vs Validação')\n",
                    "axes[1,1].set_xticks(x_pos)\n",
                    "axes[1,1].set_xticklabels(['Treino', 'Validação'])\n",
                    "axes[1,1].legend()\n",
                    "axes[1,1].grid(True, alpha=0.3)\n",
                    "\n",
                    "plt.tight_layout()\n",
                    "plt.savefig('analise_modelo_baseline.png', dpi=300, bbox_inches='tight')\n",
                    "plt.show()\n",
                    "\n",
                    "print(\"✅ Visualizações salvas como 'analise_modelo_baseline.png'\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "salvar-modelo",
                "metadata": {},
                "source": [
                    "## 9. 💾 SALVAR MODELO E RESULTADOS"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "salvar-modelo-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- SALVAR MODELO TREINADO ---\n",
                    "print(\"💾 Salvando modelo e resultados...\")\n",
                    "\n",
                    "# Criar diretório se não existir\n",
                    "os.makedirs(\"models\", exist_ok=True)\n",
                    "\n",
                    "# Salvar modelo\n",
                    "joblib.dump(modelo_baseline, \"models/modelo_baseline.pkl\")\n",
                    "print(\"✅ Modelo salvo: models/modelo_baseline.pkl\")\n",
                    "\n",
                    "# Salvar feature importance\n",
                    "importancia_features.to_csv(\"models/feature_importance_baseline.csv\", index=False)\n",
                    "print(\"✅ Feature importance salva: models/feature_importance_baseline.csv\")\n",
                    "\n",
                    "# Salvar métricas em dicionário\n",
                    "resultados_baseline = {\n",
                    "    'metricas_treino': metricas_treino,\n",
                    "    'metricas_validacao': metricas_validacao,\n",
                    "    'diferenca_r2': diferenca_r2,\n",
                    "    'top_5_features': importancia_features.head(5).to_dict(),\n",
                    "    'modelo': 'LinearRegression',\n",
                    "    'timestamp': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')\n",
                    "}\n",
                    "\n",
                    "print(\"\\n📦 RESUMO DOS ARQUIVOS GERADOS:\")\n",
                    "print(\"   ✅ models/modelo_baseline.pkl\")\n",
                    "print(\"   ✅ models/feature_importance_baseline.csv\") \n",
                    "print(\"   ✅ analise_modelo_baseline.png\")\n",
                    "print(\"   ✅ Dicionário 'resultados_baseline' disponível\")"
                ]
            },
            {
                "cell_type": "markdown",
                "id": "relatorio-final",
                "metadata": {},
                "source": [
                    "## 10. 📋 RELATÓRIO FINAL E PRÓXIMOS PASSOS"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "id": "relatorio-final-codigo",
                "metadata": {},
                "outputs": [],
                "source": [
                    "# --- RELATÓRIO EXECUTIVO FINAL ---\n",
                    "print(\"=\" * 70)\n",
                    "print(\"🎯 RELATÓRIO FINAL - MODELO BASELINE\")\n",
                    "print(\"=\" * 70)\n",
                    "\n",
                    "print(f\"\\n📈 PERFORMANCE DO MODELO:\")\n",
                    "print(f\"   🟢 R² Treino:     {metricas_treino['R²']:.4f}\")\n",
                    "print(f\"   🟡 R² Validação:  {metricas_validacao['R²']:.4f}\")\n",
                    "print(f\"   🔍 Diferença:     {diferenca_r2:.4f}\")\n",
                    "\n",
                    "print(f\"\\n🎯 TOP 3 FEATURES MAIS INFLUENTES:\")\n",
                    "for i, row in importancia_features.head(3).iterrows():\n",
                    "    impacto = \"POSITIVO\" if row['Coeficiente'] > 0 else \"NEGATIVO\"\n",
                    "    print(f\"   {i+1}. {row['Feature']} → Impacto {impacto}\")\n",
                    "\n",
                    "print(f\"\\n📊 INTERPRETAÇÃO DOS RESULTADOS:\")\n",
                    "if metricas_validacao['R²'] > 0.7:\n",
                    "    print(\"   ✅ EXCELENTE - Modelo explica mais de 70% da variância\")\n",
                    "    print(\"   💡 Insight: Features atuais são muito preditivas\")\n",
                    "elif metricas_validacao['R²'] > 0.5:\n",
                    "    print(\"   ⚠️  BOM - Modelo explica 50-70% da variância\")\n",
                    "    print(\"   💡 Insight: Base sólida para melhorias\")\n",
                    "elif metricas_validacao['R²'] > 0.3:\n",
                    "    print(\"   🔶 MODERADO - Modelo explica 30-50% da variância\")\n",
                    "    print(\"   💡 Insight: Espaço significativo para melhorias\")\n",
                    "else:\n",
                    "    print(\"   ❌ BAIXO - Modelo explica menos de 30% da variância\")\n",
                    "    print(\"   💡 Insight: Necessidade de feature engineering\")\n",
                    "\n",
                    "print(f\"\\n🚀 RECOMENDAÇÕES PARA PRÓXIMAS ETAPAS:\")\n",
                    "if metricas_validacao['R²'] < 0.6:\n",
                    "    print(\"   1. 🔥 Testar algoritmos mais complexos (Random Forest, XGBoost)\")\n",
                    "    print(\"   2. 🎯 Feature engineering adicional\")\n",
                    "    print(\"   3. ⚙️  Otimização de hiperparâmetros\")\n",
                    "else:\n",
                    "    print(\"   1. ✅ Validar performance com dados de teste\")\n",
                    "    print(\"   2. 🔧 Fine-tuning do modelo atual\")\n",
                    "    print(\"   3. 🚀 Preparar para deploy em produção\")\n",
                    "\n",
                    "print(f\"\\n💡 PRÓXIMA ETAPA: MODELOS AVANÇADOS\")\n",
                    "print(\"   • Comparar com Random Forest, Gradient Boosting\")\n",
                    "print(\"   • Otimizar hiperparâmetros\")\n",
                    "print(\"   • Selecionar melhor modelo para deploy\")\n",
                    "\n",
                    "print(\"\\n\" + \"=\" * 70)\n",
                    "print(\"🎉 ETAPA 3 CONCLUÍDA COM SUCESSO!\")\n",
                    "print(\"=\" * 70)"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    
    # Salvar como arquivo .ipynb
    with open('03_Modelo_Baseline.ipynb', 'w', encoding='utf-8') as f:
        json.dump(notebook_content, f, indent=2, ensure_ascii=False)
    
    print("✅ NOTEBOOK CRIADO COM SUCESSO!")
    print("📓 Arquivo: 03_Modelo_Baseline.ipynb")
    print("🚀 Abra no Jupyter e execute célula por célula!")

if __name__ == "__main__":
    create_baseline_notebook()